repos:
  # General pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json       # Validate JSON files
        files: \.json$
      - id: check-added-large-files

  # Terraform hooks
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.90.0
    hooks:
      - id: terraform_fmt   # Format .tf files
      - id: terraform_validate  # Validate Terraform configs
      - id: terraform_tflint    # Run tflint (if installed)
